spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: todo
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    enabled: false
  sql:
    init:
      platform: postgres
